import os
import random
import base64
import pickle
import googleapiclient.discovery
import googleapiclient.errors
from googleapiclient.http import MediaFileUpload
import yt_dlp

# --- KONFIGURASI HUNTER ---
KEYWORDS = ["funny cats", "satisfying video", "lofi hip hop", "life hacks"] 
SEARCH_LIMIT = 10  

def get_youtube_client():
    token_data = base64.b64decode(os.environ.get('TOKEN_PICKLE_BASE64'))
    credentials = pickle.loads(token_data)
    return googleapiclient.discovery.build("youtube", "v3", credentials=credentials)

def hunter_mode(youtube):
    keyword = random.choice(KEYWORDS)
    print(f"🔍 Hunter Mode: Mencari video untuk: '{keyword}'...")
    request = youtube.search().list(
        q=keyword,
        part="snippet",
        maxResults=SEARCH_LIMIT,
        type="video",
        videoDuration="short",
        relevanceLanguage="en"
    )
    response = request.execute()
    video_item = random.choice(response['items'])
    return video_item['id']['videoId'], video_item['snippet']['title']

def download_video(video_id):
    url = f"https://www.youtube.com/watch?v={video_id}"
    ydl_opts = {
        'format': 'best',
        'outtmpl': 'input_video.mp4',
    }
    with yt_dlp.YoutubeDL(ydl_opts) as ydl:
        ydl.download([url])
    return "input_video.mp4"

def upload_to_shorts(youtube, file_path, title):
    print(f"📤 Mengunggah ke YouTube Shorts...")
    request_body = {
        "snippet": {
            "title": f"{title} #shorts #viral",
            "description": "Auto-generated by Ghost-Writer V3",
            "categoryId": "22" 
        },
        "status": {"privacyStatus": "public", "selfDeclaredMadeForKids": False}
    }
    media = MediaFileUpload(file_path, chunksize=-1, resumable=True)
    youtube.videos().insert(part="snippet,status", body=request_body, media_body=media).execute()
    print(f"✅ Berhasil Upload!")

def cleanup():
    if os.path.exists("input_video.mp4"):
        os.remove("input_video.mp4")
        print("清理 🗑️ File sampah dihapus.")

if __name__ == "__main__":
    try:
        y_client = get_youtube_client()
        v_id, v_title = hunter_mode(y_client)
        file = download_video(v_id)
        upload_to_shorts(y_client, file, v_title)
    except Exception as e:
        print(f"❌ Error: {e}")
    finally:
        cleanup()
